### ISSUE TITLE
needed to install `fs` dependency before `blogyaml`

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/blogyaml#12]
Got this error msg:
`> devtools::install_github("ropenscilabs/blogyaml")`
`ERROR: dependency ‘fs’ is not available for package ‘blogyaml’`
`* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/blogyaml’`
`Installation failed: Command failed (1)`

After installing `fs`, `blogyaml` launched just fine

**Comment by maelle** [comment]
Thanks! I need to update DESCRIPTION sorry 🙈

**Comment by maelle** [comment]
Mmmh fs is in DESCRIPTION, I hadn't seen the error was at installation. Such things happen with `devtools::install_github`. If the app then worked fine, then all dependencies have been declared.
